#release configuration
#Sat Mar 28 16:17:55 CET 2026
completedPhase=check-poms
exec.activateProfiles=jboss-release
exec.additionalArguments=-DskipTests
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean install
project.scm.org.wildfly.security.vault\:wildfly-vault-feature-pack.empty=true
project.scm.org.wildfly.security.vault\:wildfly-vault-galleon-local.empty=true
project.scm.org.wildfly.security.vault\:wildfly-vault-galleon-shared.empty=true
project.scm.org.wildfly.security.vault\:wildfly-vault-parent.connection=scm\:git\:git@github.com\:wildfly-security-incubator/wildfly-vault-feature-pack.git
project.scm.org.wildfly.security.vault\:wildfly-vault-parent.developerConnection=scm\:git\:git@github.com\:wildfly-security-incubator/wildfly-vault-feature-pack
project.scm.org.wildfly.security.vault\:wildfly-vault-parent.tag=HEAD
project.scm.org.wildfly.security.vault\:wildfly-vault-parent.url=https\://github.com/wildfly-security-incubator/wildfly-vault-feature-pack
project.scm.org.wildfly.security.vault\:wildfly-vault-subsystem.empty=true
project.scm.org.wildfly.security.vault\:wildfly-vault-tests.empty=true
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=false
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tagNameFormat=@{project.version}
scm.url=scm\:git\:git@github.com\:wildfly-security-incubator/wildfly-vault-feature-pack
